### PR TITLE
Fix Item list sku name not displaying issue and remove unwanted toast message

### PR DESCRIPTION
**Pull request by Jayendra88**
#### What does this PR do? \*
Quote create and quote view pages has cart item table. second column of the cart item table contains `skuName`, which doesn't have full sku name, so i changed that column to `name` property in cart items.

handleCartSave function had unnecessary toast message (error), so I removed that message

#### How to test it? \*

[https://clouda--ecowaterb2b.myvtex.com/](https://clouda--ecowaterb2b.myvtex.com/)

go to this workspace and add multiple items to the cart and try to save cart feature in minicart section.

Before: 
image

After: 
image

### CODE REVIEW

**Comment by Jayendra88** [comment]
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually disappointed

**Comment by Jayendra88** [comment]
> Beep boop 
> 
> I noticed you didn't make any changes at the `docs/` folder
> 
> * [x]  There's nothing new to document thinking
> * [ ]  I'll do it later disappointed
> 
> In order to keep track, I'll create an issue if you decide now is not a good time
> 
> * [ ]  I just updated tadatada

**Comment by wender** [comment]
Hi @Jayendra88 thanks for the PR.
your solution may solve one your current problem, but not in a general way, may stores have their SKU names properly described, maybe your approach should focus on delivering a full information e.g *Product Name (SKU Name)*, you can change the rendering for the cell using `cellRenderer` if the `rowData.name` is different from the `rowData.skuName`, many companies uses same Product Name and SKU Name when they only have 1 SKU per product

**Comment by Jayendra88** [comment]
> Hi @Jayendra88 thanks for the PR.
> your solution may solve your current problem, but not in a general way, many stores have their SKU names properly described, maybe your approach should focus on delivering a full information e.g _Product Name (SKU Name)_, you can change the rendering for the cell using `cellRenderer` if the `rowData.name` is different from the `rowData.skuName`, many companies uses same Product Name and SKU Name when they only have 1 SKU per product
> 
> ```
> skuName: {
>         title: translateMessage({
>           id: 'store/orderquote.cartList.label.itemName',
>         }),
>         // eslint-disable-next-line react/display-name
>         cellRenderer: ({ rowData }: any) => {
>           return rowData.skuName !== rowData.name ? (
>             <div>
>               <span>{rowData.name}</span>
>               <br />
>               <span className="t-mini">{rowData.skuName}</span>
>             </div>
>           ) : (
>             rowData.skuName
>           )
>         },
>         minWidth: 300,
>       },
> ```
> 
> Change the table density to _medium_

Thank you vendor I have done the fix

I put `name` instead of `skuName` because checkout page is showing the correct sku name for the same product, Then i thought  checkout was using `name` property to display the sku name.

**Review by wender — APPROVED** [review]

**Pull request merged**
